export const PLAN_REQUEST_JOBS_SUCCEEDED = "PLAN_REQUEST_JOBS_SUCCEEDED";
export const PLAN_SET_TIMESPAN = "PLAN_SET_TIMESPAN";
export const TECHMAPS_REQUEST_SUCCEEDED = "TECHMAPS_REQUEST_SUCCEEDED";
export const STAFF_REQUEST_SUCCEEDED = "STAFF_REQUEST_SUCCEEDED";
export const MOVE_JOB = "MOVE_JOB";